CoordgenMinimizer.cpp
I noticed this as I was running valgrind across the RDKit-coordgen integration.
=> Fix memory leak in CoordgenMinimizer::addBendInteractionsOfMolecule

CoordgenConfig.hpp
On the RDKit side we often need to build the backend libraries statically linked. This enables that for coordgenlibs on Windows.
It's connected to https://github.com/rdkit/rdkit/pull/1910.
=> allow static builds on windows

CMakeLists.txt
Since we are adding maeparser as a library, we need to update the project's dependencies.
=> Add maeparser transitive Boost::iostreams dependency

CMakeLists.txt
Dear coordgenlibs developers,
In analogy to https://github.com/schrodinger/maeparser/pull/23 against maeparser, please add an SOVERSION to your library. The SOVERSION version you specify (here I went to "1" to reflect the major version of your library, but 0 or 18 are just as fine, you may however want to coordinate your semantics [start with 0, major version, schroedinger major version, ...] with the maeparser folks) will affect the naming of the Debian(+Ubuntu) package of your software I am creating at the very moment at [https://salsa.debian.org/science-team/schroedinger-coordgenlibs/blob/master/debian/control](https://salsa.debian.org/science-team/schroedinger-coordgenlibs/blob/master/debian/control).
Kind regards,
Steffen Möller
=> Please add SOVERSION to SONAME

CMakeLists.txt
Rename the CMake target to be coherent with the project name and the include and share subdirectories and avoid the unfortunate "libcoordgenlibs.so" naming.
=> Rename CMake target: coordgenlibs ==> coordgen

CoordgenMinimizer.cpp
these constraints were creating problems with clash minimization in the case of complicated constrained LID because they tend to take precedence over bond stretches and cause distorted images. Disabling them for now, I opened CRDGEN-247 to implement a better approach
=> CRDGEN-246 disable constraint interactions when avoiding clashes

CMakeLists.txt, README.md, appveyor.yml, example_dir/CMakeLists.txt, test/CMakeLists.txt
I have tidied up the CMakeLists.txt file and enabled testing, including a setup for using valgrind on tests.
Also:
- Made maeparser a "REQUIRED" dependency.
- Added a CMake export to the install (we don't need it, but might be useful for someone).
- Options to enable/disable building of example and/or tests.
- Updated Readme.
- Enabled testing on appveyor (they already were on travis); the appveyor script also required some fixing.
=> Enable testing + small improvements

.travis.yml
Travis CI recently changed its default ubuntu machine from Trusty Tahr (14.04) to Xenial Xerus (16.04), probably following end-of-life for Trusty.
This meant changes to the default boost and compiler versions. While gcc/g++ 4.8 is still available, the new default boost version (1.58) seems to fail linking to it.
This PR updates the .travis.yml file to continue building on the three last Ubuntu LTS releases: Trusty (it still can be used, but it has to be explicitly specified, since it is no longer the default), Xenial (the new default), and Bionic Beaver (18.04, the last released LTS).
On each platform, the build is made using its default compiler and boost version (although the automatic apt installer for Bionic seems to be broken, so that we need a workaround).
Once Trusty is finally …
=> Update Travis CI builds

.travis.yml
`sudo: false` is long deprecated, and should be removed, and it seems that the workaround is no longer required (although the "unable to resolve host" are still there): either removing the `sudo` fixes it, or Travis fixed it since I last tried.
=> Remove "sudo:false" and automated apt workaround

CoordgenFragmentBuilder.cpp, CoordgenFragmentBuilder.h, CoordgenFragmenter.cpp, CoordgenFragmenter.h, CoordgenMacrocycleBuilder.cpp, CoordgenMacrocycleBuilder.h, CoordgenMinimizer.cpp, CoordgenMinimizer.h, sketcherMinimizer.cpp, sketcherMinimizer.h, sketcherMinimizerAtom.cpp, sketcherMinimizerAtom.h, sketcherMinimizerBond.h, sketcherMinimizerConstraintInteraction.h, sketcherMinimizerFragment.cpp, sketcherMinimizerFragment.h, sketcherMinimizerMaths.h, sketcherMinimizerRing.cpp, sketcherMinimizerRing.h
I noticed that we are passing a fair amount of function arguments by value (mostly `sketcherMinimizerPointF`, vectors of pointers, and a few maps), which introduces a great deal of copy operations that we could avoid.
I made most of these arguments passed by const ref, added a few `std::move`s, and deleted some blocks of commented code I noticed. clang-format also made some minor changes.
Checked that it builds, passes the test included in #35, and that RDKit and mmshare have no problem building after these changes.
=> Reduce number of arguments passed by value

sketcherMinimizerAtom.cpp
writeStereoChemistry() was setting bond direction flags (inaccurately cause at this stage atoms usually have no coordinates) that are not cleaned up and can end up messing the stereochemistry of the final molecule. (bond directions are set at a later stage)
=> avoid setting bonds info when reading in atom stereochemistry

CoordgenFragmentBuilder.cpp, CoordgenMacrocycleBuilder.cpp, CoordgenMinimizer.cpp, sketcherMinimizer.h, sketcherMinimizerAtom.h, sketcherMinimizerClashInteraction.h, test/test_coordgen.cpp
Improve coordgen performance: #39 
When detecting clashes, do a rough binning of atoms. If both
atoms for one bond are above both atoms of the other bond, they
can't be a clash. This saves clash calculations for things that
are obviously not clashes. It has an impact on big structures
that are partially templated. (overall 15% speedup, but 40%
improvement for the worst molecules in the test case.
coordgen is still slower than RDkit's native coordinate
generation, though.
Also adds a simple test that the coordinates generated don't
have crazy bond lengths. This would have caught my earlier
misunderstanding.
=> Speed up coordgen, especially for very slow molecules

.travis.yml, CMakeLists.txt, README.md, appveyor.yml, cmake/CoordgenUtils.cmake, cmake/Findmaeparser.cmake, test/CMakeLists.txt
This aims at improving the way that the maeparser dependency is handled when building coordgen, and also makes it easier to include both in other projects. Also, it provides some documentation on how to build.
I brought in the CMake module we wrote to allow using `find_package()` to find maeparser compiled libraries, and also added another module to download maeparser from github if the library cannot be found.
Some details:
- The maeparser_DIR option now points to the install path, instead of the .cmake files, which was a bit obscure if you don't know how CMake works (this effectively changes the recommended solution from #37).
- If maeparser_DIR was specified (if it is not an empty string), maeparser's sources will NOT be used, and cmake will fail (since we expected to find a compiled …
=> Improve maeparser dependency handling

CoordgenFragmentBuilder.cpp, CoordgenFragmenter.cpp, CoordgenMacrocycleBuilder.cpp, CoordgenMacrocycleBuilder.h, CoordgenMinimizer.cpp, example_dir/example.cpp, sketcherMinimizer.cpp, sketcherMinimizer.h, sketcherMinimizerAtom.cpp, sketcherMinimizerAtom.h, sketcherMinimizerBendInteraction.h, sketcherMinimizerBond.cpp, sketcherMinimizerBond.h, sketcherMinimizerClashInteraction.h, sketcherMinimizerConstraintInteraction.h, sketcherMinimizerEZConstrainInteraction.h, sketcherMinimizerFragment.cpp, sketcherMinimizerFragment.h, sketcherMinimizerInteraction.h, sketcherMinimizerMarchingSquares.cpp, sketcherMinimizerMarchingSquares.h, sketcherMinimizerMaths.h, sketcherMinimizerMolecule.cpp, sketcherMinimizerResidue.cpp, sketcherMinimizerResidue.h, sketcherMinimizerResidueInteraction.cpp, sketcherMinimizerResidueInteraction.h, sketcherMinimizerRing.cpp, sketcherMinimizerStretchInteraction.h, test/test_coordgen.cpp
Includes:
* Applying Schrodinger's canonical clang-format settings
* Fixed one bug that clang-tidy pointed out (accessing a moved-from string!)
* Running clang-tidy's modernize fixes
* Running clang-tidy's add braces to single line statements fixer
I ran the coordgen tests and am building RDKit and Schrodinger to test there, as well.
=> Some (mostly automated) fixes to readability in coordgenlibs

.azure-pipelines/linux_build.yml, .azure-pipelines/mac_build.yml, .azure-pipelines/vs_build.yml, CMakeLists.txt, azure-pipelines.yml, example_dir/CMakeLists.txt, test/CMakeLists.txt, test/test_coordgen.cpp
This PR implements an option to switch between building shared and static libraries. This is more or less the same I did in maeparser (https://github.com/schrodinger/maeparser/pull/57). Please note that this PR depends on the one in maeparser, and should not be merged before that one.
- Added the `COORDGEN_BUILD_SHARED_LIBS` flag: `ON` == shared library, `OFF` == static. The required dependencies (boost, zlib), as well as the unit tests, will use the same linking type as specified by the flag. If maeparser needs to be built from source, it will also use the same linking type as indicated here.
- In the tests:  removed the `BOOST_TEST_DYN_LINK` macro.
- Added some new Azure pipelines to build static libs. These have also been reformatted, looking like bigger changes that they actually are. …
=> Allow static builds

templates.mae
I've verified that the maeparser can read all of these in now and, manually, that a couple of the templates that previously had stereo still match molecules with and without stereo and everything looks fine.
=> remove chirality and pseudo-chirality (s_st_Chirality and s_st_AtomNumChirality) tags

sketcherMinimizerAtom.h
The copy of the bonds vector was, seriously, 10% of total
duration for some example molecules that I looked at.
(because of copies that occured while checking whether
some atom is terminal)
Also fixes an extra copy for the ring vector, but that
doesn't have an impact that I know of. It's just odd.
=> Don't copy vector when not needed.

CoordgenFragmentBuilder.cpp, CoordgenMacrocycleBuilder.cpp, CoordgenMacrocycleBuilder.h, CoordgenMinimizer.cpp, sketcherMinimizer.cpp, sketcherMinimizerAtom.cpp, sketcherMinimizerAtom.h, sketcherMinimizerBond.cpp, sketcherMinimizerConstraintInteraction.h, sketcherMinimizerFragment.cpp, sketcherMinimizerFragment.h, sketcherMinimizerMarchingSquares.cpp, sketcherMinimizerMaths.h, sketcherMinimizerMolecule.h, sketcherMinimizerResidue.cpp, sketcherMinimizerRing.cpp, sketcherMinimizerRing.h, test/test_coordgen.cpp
Specifically, I ran these checks:
`-checks=performance-*,modernize-*,-modernize-use-noexcept,misc-throw-by-value-catch-by-reference,misc-unused-alias-decls,misc-unused-using-decls,google-readability-*,-google-readability-todo,readability-redundant-*,readability-simplify-*`
There is also a commit in here that I wrote manually, but which is in the same spirit. The manual commit is swap to use erase/remove instead of a bunch of separate erases. Just something I did while trying to understand code flow.
=> I ran clang-tidy to do some automated refactors

CoordgenFragmenter.cpp, CoordgenMacrocycleBuilder.cpp, CoordgenMinimizer.cpp, sketcherMinimizer.cpp, sketcherMinimizerAtom.cpp, sketcherMinimizerBond.cpp, sketcherMinimizerMaths.h
This could pollute other projects in which coordgen is included.
It's also just non-standard and harder to read, now that C++11
is avialable.
=> Remove foreach, which was defined in a header.

CMakeLists.txt
Some Linux distributions reserve lib for 32-bit and/or CPU agnostic files (like cmake modules and pkgconfig files) and install 64-bit libraries to lib64.
This allows for installation to GNU and FHS conformant directories.
=> Don't use hard-coded installation directories

sketcherMaeReading.h
This should never happen in a template? But it came up in some
test molecules, so I'm adding the check.
(I wrote a little test executable that ran coordgen after reading
some structures. Some test structure that I ran across
had no bonds)
=> Avoid traceback with no bonds in a structure.

CoordgenMinimizer.cpp, CoordgenMinimizer.h, sketcherMinimizerFragment.cpp, sketcherMinimizerFragment.h
By returning references and iterating over references. Copying
vectors unnecessarily can be a source of slowdown. `getAllDofs()` 
is called so frequently that this is worth about a 15% speedup
in some of the slower cases.
=> Reduce number of copies of some vectors

CMakeLists.txt
Apparently, `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_BINDIR` aren't always available by default: at least the MacOs 10.14 and cmake 3.13.5 combination doesn't have it, which causes the CMake configuration fail with the error:
```
[stderr] CMake Error at CMakeLists.txt:94 (install):
[stderr]   install TARGETS given no LIBRARY DESTINATION for shared library target
[stderr]   "coordgen".
[stderr] 
```
Forcing the inclusion of this module solves the issue.
=> Include GNUInstallDirs in CMake file

CoordgenFragmenter.h
This is required in order to be able to the static methods from this class in other libraries when using DLL linkage on windows.
It came up during the CI builds of https://github.com/rdkit/rdkit/pull/3319
=> add EXPORT_COORDGEN to CoordgenFragmenter class

.azure-pipelines/vs_build.yml, CoordgenConfig.hpp, azure-pipelines.yml
Apparently, clang doesn't correctly handle type comparisons with mismatched visibility: even if a library is compiled with default visibility, if the code linking it compiles using "hidden" visibility, types won't be correctly matched, creating problems at least in catching exceptions.
This is better explained in the last few comments in rdkit/rdkit/issues/2753. There are also some links to a proof of concept I built to demonstrate the problem with the RDKit.
=> Add visibility attribute to import declaration

sketcherMinimizer.cpp, sketcherMinimizer.h, test/nonterminalMetalZobs.mae, test/test_coordgen.cpp
Always trust bond order for terminal metals (in other words never convert bonds to terminal atoms to zero order bonds), this means that terminal atoms are treated as part of the same molecule for depiction purposes, so the bond is always a standard length.
=> COORDGEN-262

CMakeLists.txt, CoordgenFragmentBuilder.cpp, CoordgenFragmenter.h, CoordgenMacrocycleBuilder.cpp, sketcherMinimizer.cpp, sketcherMinimizer.h, sketcherMinimizerAtom.cpp
We're hoping to do another round of performance improvements
and code cleanup on coordgen. This commit removes some header
inclusion to lower the build-time cost of header changes.
=> Minor header cleanup, make warnings=error the default.

test/coordgenBasicSMILES.h
The build on linux with GCC 6.4.0 fails with the errors below. This patch fixes it.
```
/home/rodrigue/Documents/code/coordgenlibs/coordgenlibs/test/coordgenBasicSMILES.h: In function ‘sketcherMinimizerMolecule* schrodinger::approxSmilesParse(const string&)’:
/home/rodrigue/Documents/code/coordgenlibs/coordgenlibs/test/coordgenBasicSMILES.h:36:17: error: converting to ‘std::stack<std::stack<sketcherMinimizerAtom*> >::value_type {aka std::stack<sketcherMinimizerAtom*>}’ from initializer list would use explicit constructor ‘std::stack<_Tp, _Sequence>::stack(_Sequence&&) [with _Tp = sketcherMinimizerAtom*; _Sequence = std::deque<sketcherMinimizerAtom*, std::allocator<sketcherMinimizerAtom*> >]’ [-Werror]
tree.push({});
^
/home/rodrigue/Documents/code/coordgenlibs/coordgenlibs/test/coordgenBas …
```
=> Fix linux build with older GCC (6.4.0)

CoordgenMinimizer.cpp
Reported in the schrödinger bug tracker as SHARED-7789
Our performance monitoring tests noticed that coordgen got about
10x slower after PR #81. I guess the inner loop of minimization
must be hitting the max pretty frequently! We should address
that too.
(this doubles the max iterations from before #81, but that's ok
because #81 included a tidy refactor that halved the calls to this
function)
Before this commit:
slowest:  1.442s
average: 0.044s
After this commit:
slowest: 0.151s
average: 0.006s
molecules above 0.1s: 12
molecules above 1s: 0
=> Address recent performance regression

CoordgenFragmenter.cpp, CoordgenFragmenter.h, CoordgenMinimizer.cpp, sketcherMinimizerFragment.cpp, sketcherMinimizerFragment.h, test/test_coordgen.cpp
This is my attempt (inspired by [Paolo's PR](https://github.com/schrodinger/coordgenlibs/pull/91)) to prohibit flipping fragments that are in a given scaffold/template unless the flip would not affect constrained atoms. The problem I ran into when testing the previous changes was that some 1-2 atom fragments with exactly 1 constrained atom would not be considered constrained, allowing them to flip. Now, these specific fragments can only flip if they have no constrained children. Here is an example of where this seemed to help:
Original molecule and the scaffold:
<p float="left">
</p>
Generating coordinates with [these](https://github.com/schrodinger/coordgenlibs/pull/91) changes:
Now when generating coordinates, the 13-14 fragment is considered constrained because it has constrained …
=> CRDGEN-255: Do not allow constrained fragments to flip

sketcherMinimizerFragment.cpp
I noticed some chains were flipped, and I think it was because the FLIP_CONSTRAINED_FRAGMENT_PENALTY was not being applied when BREAK_CHAIN_PENALTY was. I should've fixed this in the last PR :)
=> Allow two penalties to be used in getCurrentPenalty

CoordgenMinimizer.cpp, CoordgenMinimizer.h
When tracking the energy after each force field minimization step, we noticed that the energy tends to 'converge' far before hitting 1000 iterations:
For many of these molecules, there is still a small energy decrease over every few iterations after converging (however the energy levels tend to oscillate). I started looking into how small changes in energy (~10-50) impact coordinates, and it does not seem to make a huge visual difference. For example, this is the energy after each iteration for one molecule:
And here is a short animation that shows how the coordinates change on each iteration:
https://user-images.githubusercontent.com/39069546/116486757-33c8b980-a843-11eb-860f-dd467d8b7705.mov
The energy drops by around 50 between iterations 200 and 1000, however most of the significant …
=> Stop force field minimization when energy improvement slows down

azure-pipelines.yml
I was doing some work when I noticed that Azure is retiring the Ubuntu 16.04 image (Support for Ubuntu LTS releases lasts for 5 years, so 16.04 expired last April):
I'm replacing it with the next Ubuntu LTS release, 18.04, which will last for another 2 years.
=> Bump Azure Ubuntu img to 18.04 LTS

sketcherMinimizerAtom.cpp
This fixes the problem on the RDKit side and doesn't break `test_coordgen` for me.
=> Fixes #106

CoordgenMinimizer.cpp, sketcherMinimizerAtom.cpp, test/test_coordgen.cpp
Although the SEGV when coordinates are NaN has already been
bypassed, I refactored this function when trying to understand
what it did. I find this version more readable, it also happens
to be more efficient (although that probably doesn't matter
with 3-5 substituents).
See @greglandrum 's https://github.com/schrodinger/coordgenlibs/pull/107
=> Refactor clockwiseOrderedNeighbors() to avoid NaN SEGV from #106

README.md
This just wraps lines in the README at 80 characters. Rationale:
1. Fits the text on the screens of editor
2. Slightly cleaner diffs if we change the text (all the changes for a paragraph won't be on a single line).
=> Enforce 80 character line limit in README

CoordgenFragmentBuilder.cpp, sketcherMinimizer.cpp, sketcherMinimizerAtom.cpp
Building coordgen under emscripten, which uses a more recent clang version than CI (15.0.6 ?) revealed that 3 variables (`neighborsN`, `level` and `partnersAlreadySet`) were being set/updated, but never used. This commit removes these variables. The rest of the changes are just clang-format.
=> Drop some set but unused variables.

CMakeLists.txt
Without this, the `coordgen` target in the exported .cmake file only specifies the coorden lib link target, but not the includes. that should be added to any target that builds/links against it.
=> Export the include directory to the .cmake file

CMakeLists.txt
https://cmake.org/cmake/help/v3.2/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file
This will install `${CMAKE_INSTALL_LIBDIR}/cmake/coordgen-config-version.cmake`, which would be helpful for `find_package` versioning.
=> build: use `PROJECT_VERSION` and install `coordgen-config-version.cmake`

CoordgenMacrocycleBuilder.h
The existing `vertexCoords::operator<` is invalid for some coordinates.  For example for `a = vertexCoords(1, 0, 0)` and `b = vertexCoords(0, 1, 0)`, both `a < b` and `b < a` return true, which isn't valid.  This is hit in the use of `set<vertexCoords>` in `CoordgenMacrocycleBuilder::scorePathRestraints`.  Windows debug builds will throw an exception if a pair of coordinates has both `a < b` and `b < a` in `std::set`, which is how this bug was found, via tests in the RDKit.  This change fixes the condition.
=> Fixed bug in vertexCoords::operator<
